# Site settings
title: Será que androids sonham com ovelhas eletrônicas?
email: maxigor.ferreira@gmail.com
description: Um blog sobre tudo e sobre nada.
url: "http://blog.maxigor.com.br" # the base hostname & protocol for your site
twitter_username: maxigor
github_username:  maxigor

# Build settings
markdown: kramdown
permalink: /:title

#default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Max Igor"